### ISSUE TITLE
./build.sh fails (packages/app-desktop: No such file or directory)

### ISSUE THREAD

**Issue by bzodonnell** [MichaelDavidHarry/joplin-armv7l#3]
Hi! First of all, thank you so much for this! I've used it for a while now to use Joplin on the Raspberry Pi on my TV and in my office. However, today the build failed, and I'm not sure why. I posted what I got from chroot here (just in case it's just some error on my end).

```
root@classpi:/# ./build.sh 
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Cloning into 'joplin'...
remote: Enumerating objects: 158938, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (42/42), done.
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 2144 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: index-pack failed
./build.sh: line 7: cd: joplin: No such file or directory
fatal: not a git repository (or any of the parent directories): .git
yarn install v1.22.22
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 0.11s.
yarn install v1.22.22
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.04s.
./build.sh: line 17: cd: packages/app-desktop: No such file or directory
jq: error: Could not open file package.json: No such file or directory
Need to install the following packages:
electron-builder@24.13.3
Ok to proceed? (y) y

npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
  • electron-builder  version=24.13.3 os=6.6.31+rpt-rpi-v8
  ⨯ /package.json: Unexpected end of JSON input  failedTask=build stackTrace=SyntaxError: /package.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at _readFile (/root/.npm/_npx/009083ec26dc578f/node_modules/jsonfile/index.js:25:16)
    at readPackageJson (/root/.npm/_npx/009083ec26dc578f/node_modules/app-builder-lib/src/util/packageMetadata.ts:10:16)
    at Packager.build (/root/.npm/_npx/009083ec26dc578f/node_modules/app-builder-lib/src/packager.ts:314:25)
    at executeFinally (/root/.npm/_npx/009083ec26dc578f/node_modules/builder-util/src/promise.ts:12:14)
root@classpi:/# ./build.sh 
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Cloning into 'joplin'...
remote: Enumerating objects: 158938, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (42/42), done.
error: 3403 bytes of body are still expected.14 MiB | 1.06 MiB/s  
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: index-pack failed
./build.sh: line 7: cd: joplin: No such file or directory
fatal: not a git repository (or any of the parent directories): .git
yarn install v1.22.22
error SyntaxError: /package.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /usr/lib/node_modules/yarn/lib/cli.js:1629:59
    at Generator.next (<anonymous>)
    at step (/usr/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/lib/node_modules/yarn/lib/cli.js:321:13
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
yarn install v1.22.22
error SyntaxError: /package.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /usr/lib/node_modules/yarn/lib/cli.js:1629:59
    at Generator.next (<anonymous>)
    at step (/usr/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/lib/node_modules/yarn/lib/cli.js:321:13
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
./build.sh: line 17: cd: packages/app-desktop: No such file or directory
  • electron-builder  version=24.13.3 os=6.6.31+rpt-rpi-v8
  ⨯ /package.json: Unexpected end of JSON input  failedTask=build stackTrace=SyntaxError: /package.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at _readFile (/root/.npm/_npx/009083ec26dc578f/node_modules/jsonfile/index.js:25:16)
    at readPackageJson (/root/.npm/_npx/009083ec26dc578f/node_modules/app-builder-lib/src/util/packageMetadata.ts:10:16)
    at Packager.build (/root/.npm/_npx/009083ec26dc578f/node_modules/app-builder-lib/src/packager.ts:314:25)
    at executeFinally (/root/.npm/_npx/009083ec26dc578f/node_modules/builder-util/src/promise.ts:12:14)
```

**Comment by MichaelDavidHarry** [comment]
@bzodonnell  Thank you for the feedback! Sorry for the late reply. Based on the log messages, it looks like something is going wrong when the script is pulling code from the Joplin repository (looks like it may be a network-related error). Does this keep happening if you delete the joplin folder inside the chroot and try to run the build.sh script again?

When I try to run the build.sh (for the 64-bit build), I see this at the beginning when it is pulling code from the Joplin repository:
```
root@raspberrypi4:/# ./build.sh
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US)
Cloning into 'joplin'...
remote: Enumerating objects: 159204, done.
remote: Counting objects: 100% (288/288), done.
remote: Compressing objects: 100% (207/207), done.
remote: Total 159204 (delta 114), reused 193 (delta 78), pack-reused 158916
Receiving objects: 100% (159204/159204), 447.05 MiB | 16.67 MiB/s, done.
Resolving deltas: 100% (120046/120046), done.
Updating files: 100% (5842/5842), done.
Note: switching to 'v3.0.12'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at a64d6e327 Desktop release v3.0.12
```
